spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/thefrontpage
    driverClassName: org.h2.Driver
    username: sa
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true